services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/home/app/web/static
    depends_on:
      - django

  django:
    build: .
    command: gunicorn betterhtwk2ical.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
    environment:
      WAIT: 1
      SQL_HOST: db
      SQL_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: production
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  static_volume: