# Generated by Django 4.0.4 on 2022-06-11 10:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import myapp1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('sg_url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('workgroups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.group')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ModuleWorkgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workgroup', models.CharField(max_length=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.module')),
            ],
            options={
                'unique_together': {('module', 'workgroup')},
            },
        ),
        migrations.CreateModel(
            name='ModuleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=200)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.module')),
            ],
            options={
                'unique_together': {('module', 'custom_name')},
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('secret', models.CharField(default=myapp1.models.generate_secret, max_length=8, unique=True)),
                ('aliases', models.ManyToManyField(to='myapp1.modulealias')),
                ('groups', models.ManyToManyField(to='myapp1.group')),
                ('modules', models.ManyToManyField(to='myapp1.module')),
                ('workgroups', models.ManyToManyField(to='myapp1.moduleworkgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('weekday', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('workgroups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('modules', models.ManyToManyField(to='myapp1.module')),
            ],
        ),
    ]
